info:
  contact: {}
  description: ts+gin 开发实战
  title: Go-web 开发
  version: 0.0.1
paths:
  /api/v1/public/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录详情表述
      produces:
      - application/json
      responses:
        "200":
          description: 登入成功
          schema:
            type: string
        "401":
          description: 登入失败
          schema:
            type: string
      summary: 用户登录
swagger: "2.0"
